services:
  hbbs:
    container_name: dxdesk-hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r ${RELAY_HOST:-204.216.171.102}:21117 -k _
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: always

  hbbr:
    container_name: dxdesk-hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: always
