name: Build DxDesk Clients

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]

env:
  RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
  RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      - name: Install LLVM
        run: choco install -y llvm

      - name: Build Flutter Windows
        run: |
          cd flutter
          flutter pub get
          flutter build windows --release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DxDesk-Windows-x64
          path: flutter/build/windows/x64/runner/Release/*
